# Generated by Django 3.2.6 on 2021-09-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок новости')),
                ('text', models.TextField(verbose_name='текст новости')),
                ('is_published', models.BooleanField(default=False)),
                ('description', models.TextField(default='', verbose_name='краткое описание новости')),
                ('published_at', models.DateTimeField(null=True, verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
    ]
