# Generated by Django 3.2.6 on 2021-09-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-published_at'], 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
