# Generated by Django 3.2.6 on 2021-09-02 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0004_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminstance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='app_goods.item', verbose_name='товар'),
        ),
    ]
