# Generated by Django 3.2.6 on 2021-09-08 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, verbose_name='тип жилья')),
            ],
            options={
                'verbose_name': 'тип жилья',
                'verbose_name_plural': 'типы жилья',
            },
        ),
        migrations.CreateModel(
            name='RoomsQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=64, verbose_name='количество комнат')),
            ],
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='название жилья')),
                ('description', models.TextField(verbose_name='описание жилья')),
                ('price', models.PositiveIntegerField(verbose_name='цена жилья')),
                ('rooms_quantity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numbers', to='app_housings.roomsquantity')),
            ],
            options={
                'verbose_name': 'жилище',
                'verbose_name_plural': 'жилища',
            },
        ),
    ]
