# Generated by Django 3.2.6 on 2021-09-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_housings', '0002_alter_roomsquantity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='app_housings.housingtype'),
        ),
    ]
