# Generated by Django 3.2.6 on 2021-09-08 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_housings', '0003_housing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='rooms_quantity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numbers', to='app_housings.roomsquantity', verbose_name='количество комнат'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='app_housings.housingtype', verbose_name='тип жилья'),
        ),
    ]
