# Generated by Django 2.2 on 2021-08-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification',
            field=models.BooleanField(choices=[(True, 'верифицирован'), (False, 'не верифицирован')], default=False, verbose_name='верификация'),
        ),
    ]
