# Generated by Django 2.2 on 2021-08-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(blank=True, verbose_name='balance'),
        ),
    ]
