# Generated by Django 3.2.6 on 2021-08-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='amount_purchases',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='баланс'),
        ),
    ]
