# Generated by Django 3.2.6 on 2021-09-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_auto_20210901_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='amount_purchases',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='сумма покупок'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='баланс'),
        ),
    ]
