# Generated by Django 2.2 on 2021-07-29 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_auto_20210729_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='what_new',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_news.New', verbose_name='новость'),
        ),
        migrations.AlterField(
            model_name='new',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата изменения'),
        ),
    ]
