# Generated by Django 2.2 on 2021-07-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0005_auto_20210729_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='activity',
            field=models.BooleanField(choices=[(True, 'активна'), (False, 'не активна')], default=True, verbose_name='активность'),
        ),
    ]
