# Generated by Django 2.2 on 2021-08-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0008_auto_20210801_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='', max_length=1000, verbose_name='текст комментария'),
        ),
    ]
