# Generated by Django 2.2 on 2021-08-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0009_auto_20210801_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='имя пользователя'),
        ),
    ]
