# Generated by Django 2.2 on 2021-08-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0010_auto_20210801_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='activity',
            field=models.BooleanField(choices=[(True, 'активна'), (False, 'не активна')], default=False, verbose_name='активность'),
        ),
    ]
