# Generated by Django 2.2 on 2021-08-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0011_auto_20210803_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='tag',
            field=models.CharField(blank=True, max_length=12, verbose_name='тэг'),
        ),
    ]
